version: "3"
services:
  database:
    build:
      context: database
    environment:
      - user="1000:1001"
    expose:
      - 5432
    ports:
      - "15432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - fakepay
networks:
  fakepay:
